apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: jupyter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-app
  template:
    metadata:
      labels:
        app: jupyter-app
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: jupyter
        image: chunjaedwpark/my-jupyter-app:0312
        ports:
        - name: http
          containerPort: 8888
          protocol: TCP
        volumeMounts:
        - name: notebook-data
          mountPath: /home/jovyan
      initContainers:
      - name: change-ownership-container
        image: busybox
        command: ["/bin/chown", "-R", "1000:1000", "/home/jovyan"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: notebook-data
          mountPath: /home/jovyan
      volumes:
      - name: notebook-data
        persistentVolumeClaim:
          claimName: jupyter-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-app-interface
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: jupyter-app
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888